README.md, integration-example.php, src/Perimeterx.php, src/PerimeterxActivitiesClient.php
This adds the ability to pass a custom activity handler so activity and detection results can be passed to internal systems to be recorded.
=> Add additional activity handler

src/PerimeterxHttpClient.php
1. Recursively walk on array values which are of stdClass
2. Make a "fixBody" function public so it can be used by custom_risk_handler
=> Fix bug in fixing json to be utf8 encoded

.gitignore, .travis.yml, README.md, composer.json, examples/customize_block_page/index.php, src/Perimeterx.php, src/PerimeterxException.php, src/templates/block.mustache, src/templates/captcha.mustache, tests/PerimeterxConfigurationValidatorTest.php
added mustache to project (template engine)
updated README file
added validation for pxConfig
=> EN-2704 - redesign the pages

composer.json, src/Perimeterx.php, tests/PerimeterxConfigurationValidatorTest.php
- added px_orig_cookie when decrypt fail
=> Version Release

src/Perimeterx.php, src/templates/captcha.mobile.mustache
1. added hostUrl variable for mobile templates to use
2. fixed escaping for hostUrl in template
=> Dev - Mustache related fixes

src/Perimeterx.php, tests/PerimeterxConfigurationValidatorTest.php
1. updated collectorUrl in mobile templates to its new value
=> EN-3954, collectorUrl property update

src/PerimeterxCookieValidator.php
1. added support for cookie with value "2"
2. added new s2s call reason
=> EN-4084 handle X-PX-AUTHORIZATION of 2

src/PerimeterxCookieValidator.php
1) added support for new mobile sdk header "3"
=> EN-4424 Added support for "mobile_sdk_pinning_error" header

src/PerimeterxContext.php, src/PerimeterxCookieValidator.php
1) Transformed all headers to be uppercase for PHP to check properly
2) updated check for numeric px authorization header
=> Mobile sdk related issues

src/PerimeterxContext.php
1) removed duplicate call to getAllHeaders
=> small headers related fix

src/CookieV1.php, src/Perimeterx.php, src/PerimeterxCaptchaValidator.php, src/PerimeterxContext.php, src/PerimeterxCookieValidator.php, src/PerimeterxLogger.php, src/PerimeterxS2SValidator.php, tests/PerimeterxCookieV3ValidatorTest.php, tests/PerimeterxCookieValidatorTest.php
1) Fixed debug_mode flag for outputting logs
2) Updated log messages
=> EN-4835 Logging improvements

.travis.yml, src/PerimeterxContext.php, src/PerimeterxCookieValidator.php, src/PerimeterxPayload.php, src/PerimeterxS2SValidator.php, src/TokenV1.php, src/TokenV3.php, src/perimeterxOriginalTokenValidator.php, tests/PerimeterxCookieV3ValidatorTest.php, tests/PerimeterxCookieValidatorTest.php, tests/PerimeterxOriginalTokenValidatorTest.php
1) Added original token 
2) Updated tests
3) Updated logs
=> APP-214 Better handling of mobile token

src/PerimeterxActivitiesClient.php, src/PerimeterxContext.php
1) added activity type of simulated_block
=> APP-220 Added simulated_block

src/Perimeterx.php, src/PerimeterxContext.php, src/PerimeterxS2SValidator.php, src/templates/ratelimit.mustache
1) added support for rate limiting.
=> APP-234 Added support for rate limiting

.travis.yml, README.md, src/Perimeterx.php, src/PerimeterxContext.php, src/PerimeterxDataEnrichment.php, src/PerimeterxS2SValidator.php, tests/PerimeterxDataEnrichmentTest.php
=> APP-528 - Data Enrichment - add support to the PHP enforcer

px_metadata.json
=> added metadata json

src/Perimeterx.php, src/PerimeterxActivitiesClient.php, src/PerimeterxContext.php, src/PerimeterxHttpClient.php, src/PerimeterxResetClient.php, src/PerimeterxS2SValidator.php, tests/PerimeterxS2SValidatorTest.php
Reverts PerimeterX/perimeterx-php-sdk#132
=> Revert "Bugfix/no pass reason"

CHANGELOG.md, README.md, composer.json, px_metadata.json, src/Perimeterx.php
* release v3.7.2
* fixed px_metadata.json to align with spec
=> release v3.7.2

src/Perimeterx.php, src/PerimeterxPayload.php
=> cookie origin issue

CHANGELOG.md, README.md, composer.json, px_metadata.json, src/Perimeterx.php, src/PerimeterxActivitiesClient.php, src/PerimeterxContext.php, src/PerimeterxFirstPartyClient.php, src/PerimeterxRiskClient.php, src/PerimeterxUtils.php, src/Utils/GuzzleHttpClient.php, src/Utils/IHttpClient.php, tests/MockHttpClient.php, tests/PerimeterxFirstPartyClientTest.php, tests/PerimeterxS2SValidatorTest.php, tests/PerimeterxUtilsTest.php, tests/TestUtils.php
https://perimeterx.atlassian.net/browse/SDKNEW-2139
=> [SDKNEW-2139] Feature/first party

CHANGELOG.md, src/Perimeterx.php, src/PerimeterxContext.php, src/PerimeterxUtils.php
* IP extraction bug fix
* Minor bugfixes from first party feature
https://perimeterx.atlassian.net/browse/SDKNEW-2139
=> [SDKNEW-2139] Bugfix/ip extraction fix

CHANGELOG.md, README.md, composer.json, px_metadata.json, src/Perimeterx.php
https://perimeterx.atlassian.net/browse/SDKNEW-2139
=> [SDKNEW-2139] release v3.10.0 (to dev)
